### ISSUE TITLE
Your model and async

### ISSUE THREAD

**Issue by kirkroyster** [AnthonyGiretti/Angular4-GoogleCharts#1]
I have no problem using your model to generate various charts such as gauges, if I define the data within a function not called within an asynchronous call-back.  But I need to load down my data from a server and after the result is returned (async model), I then load the values.  But when I load the data after an async promise is resolved, I get a message that my data values are not defined, from the chart service.ts file.

Any ideas on why the values are not being received by the service if I set them within the .then() callback after loading down data?

If I just call a function from my constructor to load the chart data with values, it all works fine.

Kirk

**Comment by AnthonyGiretti** [comment]
Hi! could you provide me a sample of your code please?

**Comment by kirkroyster** [comment]
Actually I am set, everything is functioning ok.  Thanks
